version: "3"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URI=${MONGO_URI}
  mongodb:
    image: mongo
    restart: always
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge
